[build]
  command = "pip install -r requirements.txt && uvicorn main:app --host=0.0.0.0 --port=8080"
  publish = "/"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE"

